### ISSUE TITLE
Duplicate results reported

### ISSUE THREAD

**Issue by hypnobeard** [rollem-discord/rollem-discord#43]
Sometimes, when rolling, the roll is repeated. Usually this results in a second, different set of rolls, but occasionally will result in the same set being sent twice.

Example:

> [11:56 PM] 
> BOT
>  rollem: @Hypno (Sgt. Gray), 
> 4 ⟵ [2]1d6 + 2
> 7 ⟵ [5]1d6 + 2
> 3 ⟵ [1]1d6 + 2
> 3 ⟵ [1]1d6 + 2
> [11:56 PM] 
> BOT
>  rollem: @Hypno (Sgt. Gray), 
> 5 ⟵ [3]1d6 + 2
> 6 ⟵ [4]1d6 + 2
> 3 ⟵ [1]1d6 + 2
> 7 ⟵ [5]1d6 + 2

This was one roll - 4#1d6+2; the replies came back simultaneously (or as close to such as they looked like one response to me). Occurred on Apr 23, 2020 at 11:56PM Eastern.

**Comment by david-sharer** [comment]
Thanks for the report!

To help narrow down the search for the cause:

- Does this usually happen once every now and then, happen for every roll for short time (a few minutes to an hour) and then stop, or something else?
- Next time it happens can you do '@rollem stats' - this is to see if two bots are trying to respond or if it's one double-responding for some reason? It will also help me tell if one specific shard is having issues.

The rest of this comment is mostly notes for future-me.

---

Off the top of my head, the bits that could be breaking:
1. kubernetes is starting a second bot before the first has shut down, when it decides it's time to recycle the instance. could be mitigated by adding inter-bot communication bus (via redis? doesn't k8s already have something for this?)
2. a single bot is 'receiving' the message twice (due to a network hiccup?) - could be easily mitigated by keeping a local rolling list of recently replied post IDs and refusing to process them twice
3. some mystery discord.js retry logic is causing one bot to send the reply twice. it's unclear how i would avoid this if it's the case
4. discord itself is passing the message through twice

1 or 2 could be the cause when the replies don't match. 3 and 4 when the replies do. Barring cosmically unlikely events. Or thread concurrency shenanigans that I don't think discord.js should be doing.

**Comment by hypnobeard** [comment]
It usually happens every now and then. Most of the time it's once and then stops; very rarely we've seen it double for 2-3 rolls in a row. I'll keep an eye out to do the @rollem stats

**Comment by david-sharer** [comment]
![image](https://user-images.githubusercontent.com/26589071/80290497-2a6db400-86fa-11ea-87bf-cef55accc5dd.png)

**Comment by hypnobeard** [comment]
Yes, that's exactly the issue. Haven't seen it since the report I made, unfortunately (?).
